### ISSUE TITLE
response数组编码后解码出来为空数组

### ISSUE THREAD

**Issue by fangyincheng** [dubbogo/hessian2#35]
response的body为[]string{"a}
解码后为&[ ]
测试代码修改自hessian_test.go
[新建文本文档 (4).txt](https://github.com/dubbogo/hessian2/files/3216030/4.txt)

**Comment by wongoo** [comment]
@fangyincheng  it's fixed, u can checkout and try.

**Comment by wongoo** [comment]
@fangyincheng  does it work now? I will close it if no doubt.

**Comment by fangyincheng** [comment]
> @fangyincheng does it work now? I will close it if no doubt.

thanks，it can be close.
