### ISSUE TITLE
map[interface{}][]interface{}类型的支持

### ISSUE THREAD

**Issue by fangyincheng** [dubbogo/hessian2#37]
hessian2需要支持map[interface{}][]interface{}之类的复杂类型

**Comment by wongoo** [comment]
@fangyincheng can u  provided a unit test please？

**Comment by fangyincheng** [comment]
@wongoo yes, they may be:
`doTestRequest(t, PackageRequest, Zero, []interface{}{map[string][]*Case{"key": {{A: "a", B: 3}}}})
doTestResponse(t, PackageResponse, Response_OK, map[string][]*Case{"key": {{A: "a", B: 3}}}, &map[interface{}][]interface{}{})`

**Comment by wongoo** [comment]
@fangyincheng  Currently, the supported decoding type of map is map[interface{}]interface{} , even when the type of map value is an array. see the pr https://github.com/dubbogo/hessian2/pull/44.

**Comment by fangyincheng** [comment]
@wongoo Well, it is OK. I will try it when it is merged.

**Comment by wongoo** [comment]
@fangyincheng it's merged.
