### ISSUE TITLE
Fix: list decode代码中将nil过滤掉的问题

### ISSUE THREAD

**Issue by gaoxinge** [dubbogo/hessian2#40]
https://github.com/dubbogo/hessian2/blob/master/list.go#L189-L191 这段代码将nil过滤掉，不放入list中，意思可能与hessian协议不符。

**Comment by wongoo** [comment]
@gaoxinge yes，list should support nil item，u can submit a pr with unit test about it. thanks!

**Comment by wongoo** [comment]
@gaoxinge slice support nil element only if the type of element is pointer, which must be verified when decoding. The following is a test to append nil to slice:

```go

func TestSliceAppendNil(t *testing.T) {
	type Msg struct {
		Text string
	}
	a := Msg{Text: "a"}
	c := Msg{Text: "c"}

	var list []*Msg

	list = append(list, &a)
	list = append(list, nil) // append nil
	list = append(list, &c)

	assert.Equal(t, 3, len(list))
	assert.Equal(t, "a", list[0].Text)
	assert.Nil(t, list[1])
	assert.Equal(t, "c", list[2].Text)

	var list2 []*Msg
	v := reflect.ValueOf(list)
	vv := reflect.ValueOf(list2)

	for i := 0; i < v.Len(); i++ {
		vv = reflect.Append(vv, v.Index(i)) // support append nil value
	}
	list2 = vv.Interface().([]*Msg)

	assert.Equal(t, 3, len(list2))
	assert.Equal(t, "a", list2[0].Text)
	assert.Nil(t, list2[1])
	assert.Equal(t, "c", list2[2].Text)
}
```

**Comment by gaoxinge** [comment]
@wongoo Yes, if the slice hold a concrete type (`Msg` or `*Msg`), we should consinder to verify whether the type of element is a pointer when adding a `nil`. However, we use a abstract type (`Interface{}`) in `list.go ` , which can hold anything, including `nil`.

- https://github.com/dubbogo/hessian2/blob/38ccc67445df598f0ef12020f00f6b45c6bb3470/list.go#L176
- https://github.com/dubbogo/hessian2/blob/38ccc67445df598f0ef12020f00f6b45c6bb3470/list.go#L228

**Comment by wongoo** [comment]
@gaoxinge yes, currently it [ignore the list type](https://github.com/dubbogo/hessian2/blob/c432dcada9eab283abc851c7f65760f18a0377c6/list.go#L149) and uses `[]interface{}` to accept elements, and u can submit a pr for it .

While in the future, may be we define the exact type of slice. see
https://github.com/vogo/gohessian/blob/228bdae7a821ce53f4512694969325e7d60bc264/list.go#L194

**Comment by gaoxinge** [comment]
@wongoo You are very right! Although `[]interface{}{}` is a dynamic type slice, we can't use `reflect.Append` to append a `interface{}(nil)` (or `reflect.ValueOf(nil)`) to the slice. So the code below  

https://github.com/dubbogo/hessian2/blob/eb9857f7fae12289cad801c2914fb0b5cffbff33/list.go#L181-L195

will throw a runtime error at [line 191](https://github.com/dubbogo/hessian2/blob/eb9857f7fae12289cad801c2914fb0b5cffbff33/list.go#L191) if variable `it` is `nil`.

So I raise a [question](https://stackoverflow.com/questions/56396510/how-to-append-nil-to-dynamic-type-slice-by-reflect-append), and maybe we can use [this answer](https://stackoverflow.com/a/56396855/5772365) to work around this.
