### ISSUE TITLE
java Exception class

### ISSUE THREAD

**Issue by fangyincheng** [dubbogo/hessian2#53]
**What would you like to be added**:

     Can it support Java exception classes？

**Why is this needed**:
    
    When dubbo-go's returns an exception, java need decode as Throwable.

java code:
```java
Object obj = in.readObject();
if (obj instanceof Throwable == false)
     throw new IOException("Response data error, expect Throwable, but get " + obj);
setException((Throwable) obj);
setAttachments((Map<String, String>) in.readObject(Map.class));
```

**Comment by wongoo** [comment]
@fangyincheng I think it's supported. you can define a `POJO` with a field `detailMessage` and set the `JavaClassName` to `java.lang.Throwable`. Please have a try. Expecting your result!

**Comment by fangyincheng** [comment]
@wongoo Exception is  in java SDK, so I thinks it should not be feeled by user.

**Comment by wongoo** [comment]
@fangyincheng yes, I think so! can u submit a pr for it?

**Comment by fangyincheng** [comment]
[here](https://github.com/dubbo/go-for-apache-dubbo/issues/68)
@wongoo @AlexStocks
