### ISSUE TITLE
Java Exception class supplement

### ISSUE THREAD

**Issue by fangyincheng** [dubbogo/hessian2#59]
> Explain

- Your files should be in the java_exception folder, and named in format of [exception name].go. Reference java_exception.go
- Test should be in the java_exception_test.go. Reference java_exception_test.go
- Please reply the number to represent your work, thanks.
- Welcome to add more exceptions to issue.

> 1 

* RuntimeException
* IncompleteAnnotationException
* AnnotationTypeMismatchException
* NegativeArraySizeException
* UnsupportedOperationException
* ArithmeticException

> 2

* IllegalMonitorStateException
* ArrayStoreException
* IllegalStateException
* ClassCastException
* UncheckedIOException
* EnumConstantNotPresentException

> 3

* NullPointerException
* TypeNotPresentException
* UndeclaredThrowableException
* MalformedParametersException
* WrongMethodTypeException
* MalformedParameterizedTypeException

> 4

* SecurityException
* IllegalArgumentException
* IllegalThreadStateException
* NumberFormatException
* IndexOutOfBoundsException
* ArrayIndexOutOfBoundsException
* StringIndexOutOfBoundsException

> 5

* IllegalClassFormatException
* ReflectiveOperationException
* InvocationTargetException
* NoSuchMethodException
 * NoSuchFieldException
* IllegalAccessException
* ClassNotFoundException
* InstantiationException

> 6

* CloneNotSupportedException
* UnmodifiableClassException
* InterruptedException
* LambdaConversionException
* IOException
* InterruptedIOException

> 7

* UncheckedIOException
* FileNotFoundException
* EOFException
* SyncFailedException
* ObjectStreamException
* WriteAbortedException
* InvalidObjectException
* StreamCorruptedException
* InvalidClassException
* OptionalDataException
* NotActiveException
* NotSerializableException
* UTFDataFormatException

> 8

* DateTimeException
* UnsupportedTemporalTypeException
* ZoneRulesException
* DateTimeParseException

* FormatterClosedException
* CancellationException
* UnknownFormatConversionException
* UnknownFormatFlagsException
* IllegalFormatFlagsException
* IllegalFormatPrecisionException
* IllegalFormatCodePointException
* MissingFormatArgumentException
* MissingFormatWidthException

> 9

* IllegalFormatWidthException
* IllegalFormatConversionException
* DuplicateFormatFlagsException
* MissingResourceException
* ConcurrentModificationException
* RejectedExecutionException
* CompletionException
* EmptyStackException
* IllformedLocaleException
* NoSuchElementException
* InputMismatchException
* ExecutionException
* InvalidPreferencesFormatException
* TimeoutException
* BackingStoreException
* DataFormatException
* BrokenBarrierException
* TooManyListenersException
* InvalidPropertiesFormatException
* ZipException
* JarException

**Comment by aliiohs** [comment]
i will impl 1th

**Comment by yiduwangkai** [comment]
6吧

**Comment by ckex** [comment]
2

**Comment by pantianying** [comment]
3

**Comment by comdd** [comment]
4

**Comment by sxllwx** [comment]
5

**Comment by gaoxinge** [comment]
5

**Comment by fangyincheng** [comment]
Appending:

* Welcome to continue receiving assignments.

> 7

* UncheckedIOException
* FileNotFoundException
* EOFException
* SyncFailedException
* ObjectStreamException
* WriteAbortedException
* InvalidObjectException
* StreamCorruptedException
* InvalidClassException
* OptionalDataException
* NotActiveException
* NotSerializableException
* UTFDataFormatException

> 8

* DateTimeException
* UnsupportedTemporalTypeException
* ZoneRulesException
* DateTimeParseException

* FormatterClosedException
* CancellationException
* IllegalFormatException
* UnknownFormatConversionException
* UnknownFormatFlagsException
* IllegalFormatFlagsException
* IllegalFormatPrecisionException
* IllegalFormatCodePointException
* MissingFormatArgumentException
* MissingFormatWidthException

> 9

* IllegalFormatWidthException
* IllegalFormatConversionException
* DuplicateFormatFlagsException
* MissingResourceException
* ConcurrentModificationException
* RejectedExecutionException
* CompletionException
* EmptyStackException
* IllformedLocaleException
* NoSuchElementException
* InputMismatchException
* ExecutionException
* InvalidPreferencesFormatException
* TimeoutException
* BackingStoreException
* DataFormatException
* BrokenBarrierException
* TooManyListenersException
* InvalidPropertiesFormatException
* ZipException
* JarException

**Comment by ice-summer-bug** [comment]
7

**Comment by fangyincheng** [comment]
> > Explain
> 
> * Your files should be named in format of java_[exception name].go. Reference java_exception.go
> * Test should be in the java_exception_test.go. Reference java_exception_test.go
> * Please reply the number to represent your work, thanks.
> * Welcome to add more exceptions to issue.
> 
> > 1
> 
> * RuntimeException
> * IncompleteAnnotationException
> * AnnotationTypeMismatchException
> * NegativeArraySizeException
> * UnsupportedOperationException
> * ArithmeticException
> 
> > 2
> 
> * IllegalMonitorStateException
> * ArrayStoreException
> * IllegalStateException
> * ClassCastException
> * UncheckedIOException
> * EnumConstantNotPresentException
> 
> > 3
> 
> * NullPointerException
> * TypeNotPresentException
> * UndeclaredThrowableException
> * MalformedParametersException
> * WrongMethodTypeException
> * MalformedParameterizedTypeException
> 
> > 4
> 
> * SecurityException
> * IllegalArgumentException
> * IllegalThreadStateException
> * NumberFormatException
> * IndexOutOfBoundsException
> * ArrayIndexOutOfBoundsException
> * StringIndexOutOfBoundsException
> 
> > 5
> 
> * IllegalClassFormatException
> * ReflectiveOperationException
> * InvocationTargetException
> * NoSuchMethodException
> * NoSuchFieldException
> * IllegalAccessException
> * ClassNotFoundException
> * InstantiationException
> 
> > 6
> 
> * CloneNotSupportedException
> * UnmodifiableClassException
> * InterruptedException
> * LambdaConversionException
> * IOException
> * InterruptedIOException
> 
> > 7
> 
> * UncheckedIOException
> * FileNotFoundException
> * EOFException
> * SyncFailedException
> * ObjectStreamException
> * WriteAbortedException
> * InvalidObjectException
> * StreamCorruptedException
> * InvalidClassException
> * OptionalDataException
> * NotActiveException
> * NotSerializableException
> * UTFDataFormatException
> 
> > 8
> 
> * DateTimeException
> * UnsupportedTemporalTypeException
> * ZoneRulesException
> * DateTimeParseException
> * FormatterClosedException
> * CancellationException
> * IllegalFormatException
> * UnknownFormatConversionException
> * UnknownFormatFlagsException
> * IllegalFormatFlagsException
> * IllegalFormatPrecisionException
> * IllegalFormatCodePointException
> * MissingFormatArgumentException
> * MissingFormatWidthException
> 
> > 9
> 
> * IllegalFormatWidthException
> * IllegalFormatConversionException
> * DuplicateFormatFlagsException
> * MissingResourceException
> * ConcurrentModificationException
> * RejectedExecutionException
> * CompletionException
> * EmptyStackException
> * IllformedLocaleException
> * NoSuchElementException
> * InputMismatchException
> * ExecutionException
> * InvalidPreferencesFormatException
> * TimeoutException
> * BackingStoreException
> * DataFormatException
> * BrokenBarrierException
> * TooManyListenersException
> * InvalidPropertiesFormatException
> * ZipException
> * JarException

**Comment by developersPHP** [comment]
8

**Comment by pantianying** [comment]
I will handle half of 9 .
IllegalFormatWidthException
IllegalFormatConversionException
DuplicateFormatFlagsException
MissingResourceException
ConcurrentModificationException
RejectedExecutionException
CompletionException
EmptyStackException
IllformedLocaleException
NoSuchElementException

**Comment by fangyincheng** [comment]
I will do these half of 9: 

- InputMismatchException
- ExecutionException
- InvalidPreferencesFormatException
- TimeoutException
- BackingStoreException
- DataFormatException
- BrokenBarrierException
- TooManyListenersException
- InvalidPropertiesFormatException
- ZipException
- JarException
