### ISSUE TITLE
go []string to java []string

### ISSUE THREAD

**Issue by pantianying** [dubbogo/hessian2#76]
**What would you like to be added**:

![image](https://user-images.githubusercontent.com/20589945/59604125-cf644b80-913d-11e9-97e2-3d22da90e747.png)

![image](https://user-images.githubusercontent.com/20589945/59604142-e30fb200-913d-11e9-83e3-e0db929ad06b.png)

golang数据结构中的[]string被java识别为java.util.ArrayList。后来发现是该版本hessaingolang只支持无类型list。导致图二java抛出异常。

**Why is this needed**:
   实际使用中数据结构不可控，需要支持。以上图二的代码为com.alibaba.dubbo.rpc.filter.GenericFilter的源码，也无法修改。

**Comment by wongoo** [comment]
@pantianying thanks for reporting this issue, we will work on it asap.

**Comment by gaoxinge** [comment]
I am curious how to represent java array `Object[]` in golang? Untyped or typed?

**Comment by wongoo** [comment]
@gaoxinge golang should encode that as typed list with a java array name.
