### ISSUE TITLE
bigdecimal与golang中类型对应关系问题？

### ISSUE THREAD

**Issue by wongoo** [dubbogo/hessian2#89]
**What happened**:
linked to： https://github.com/apache/dubbo-go/issues/109

**What you expected to happen**:
encode/decode support for java Bigdecimal

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by wongoo** [comment]
the key point is to find out what the encode result of java BigDecimal. 
- if it's encoded as a hessian object, then define a POJO in go to decode
- if it's encoded as a hessian double, then using float64 in go to decode

**Comment by pepigo** [comment]
```go
type BigDecimal struct {
     ...
}

func (BigDecimal) JavaClassName() string {
	return "java.math.BigDecimal"
}
```
